package br.com.marcelbraghini.infrastructure.correios.atendecliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-04-24T17:06:19.425-03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", name = "AtendeCliente")
@XmlSeeAlso({ObjectFactory.class})
public interface AtendeCliente {

    @WebMethod
    @RequestWrapper(localName = "buscaServicosAdicionaisAtivos", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosAdicionaisAtivos")
    @ResponseWrapper(localName = "buscaServicosAdicionaisAtivosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosAdicionaisAtivosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.ServicoAdicionalXML> buscaServicosAdicionaisAtivos(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "fechaPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.FechaPlp")
    @ResponseWrapper(localName = "fechaPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.FechaPlpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long fechaPlp(

        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "idPlpCliente", targetNamespace = "")
        java.lang.Long idPlpCliente,
        @WebParam(name = "cartaoPostagem", targetNamespace = "")
        java.lang.String cartaoPostagem,
        @WebParam(name = "faixaEtiquetas", targetNamespace = "")
        java.lang.String faixaEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "validaPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidaPlp")
    @ResponseWrapper(localName = "validaPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidaPlpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean validaPlp(

        @WebParam(name = "cliente", targetNamespace = "")
        long cliente,
        @WebParam(name = "numero", targetNamespace = "")
        java.lang.String numero,
        @WebParam(name = "diretoria", targetNamespace = "")
        long diretoria,
        @WebParam(name = "cartao", targetNamespace = "")
        java.lang.String cartao,
        @WebParam(name = "unidadePostagem", targetNamespace = "")
        java.lang.String unidadePostagem,
        @WebParam(name = "servico", targetNamespace = "")
        java.lang.Long servico,
        @WebParam(name = "servicosAdicionais", targetNamespace = "")
        java.util.List<java.lang.String> servicosAdicionais,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "calculaTarifaServico", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CalculaTarifaServico")
    @ResponseWrapper(localName = "calculaTarifaServicoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CalculaTarifaServicoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String calculaTarifaServico(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.String codAdministrativo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "codServico", targetNamespace = "")
        java.lang.String codServico,
        @WebParam(name = "cepOrigem", targetNamespace = "")
        java.lang.String cepOrigem,
        @WebParam(name = "cepDestino", targetNamespace = "")
        java.lang.String cepDestino,
        @WebParam(name = "peso", targetNamespace = "")
        java.lang.String peso,
        @WebParam(name = "codFormato", targetNamespace = "")
        java.lang.Integer codFormato,
        @WebParam(name = "comprimento", targetNamespace = "")
        java.lang.Double comprimento,
        @WebParam(name = "altura", targetNamespace = "")
        java.lang.Double altura,
        @WebParam(name = "largura", targetNamespace = "")
        java.lang.Double largura,
        @WebParam(name = "diametro", targetNamespace = "")
        java.lang.Double diametro,
        @WebParam(name = "codMaoPropria", targetNamespace = "")
        java.lang.String codMaoPropria,
        @WebParam(name = "valorDeclarado", targetNamespace = "")
        java.lang.Double valorDeclarado,
        @WebParam(name = "codAvisoRecebimento", targetNamespace = "")
        java.lang.String codAvisoRecebimento
    ) throws SigepClienteException, Exception_Exception, AutenticacaoException;

    @WebMethod(operationName = "VerificaSeTodosObjetosCancelados")
    @RequestWrapper(localName = "VerificaSeTodosObjetosCancelados", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaSeTodosObjetosCancelados")
    @ResponseWrapper(localName = "VerificaSeTodosObjetosCanceladosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaSeTodosObjetosCanceladosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean verificaSeTodosObjetosCancelados(

        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.ObjetoPostal> arg0
    ) throws SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "cancelarObjeto", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CancelarObjeto")
    @ResponseWrapper(localName = "cancelarObjetoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CancelarObjetoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean cancelarObjeto(

        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, Exception_Exception, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "pesquisarParametrosPorDescricao", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarParametrosPorDescricao")
    @ResponseWrapper(localName = "pesquisarParametrosPorDescricaoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarParametrosPorDescricaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.DimensaoTO pesquisarParametrosPorDescricao(

        @WebParam(name = "prefix", targetNamespace = "")
        java.lang.String prefix
    );

    @WebMethod
    @RequestWrapper(localName = "atualizaPagamentoNaEntrega", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.AtualizaPagamentoNaEntrega")
    @ResponseWrapper(localName = "atualizaPagamentoNaEntregaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.AtualizaPagamentoNaEntregaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String atualizaPagamentoNaEntrega(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "obterClienteAtualizacao", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterClienteAtualizacao")
    @ResponseWrapper(localName = "obterClienteAtualizacaoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterClienteAtualizacaoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar obterClienteAtualizacao(

        @WebParam(name = "cnpjCliente", targetNamespace = "")
        java.lang.String cnpjCliente,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "verificaDisponibilidadeServico", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaDisponibilidadeServico")
    @ResponseWrapper(localName = "verificaDisponibilidadeServicoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaDisponibilidadeServicoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verificaDisponibilidadeServico(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "numeroServico", targetNamespace = "")
        java.lang.String numeroServico,
        @WebParam(name = "cepOrigem", targetNamespace = "")
        java.lang.String cepOrigem,
        @WebParam(name = "cepDestino", targetNamespace = "")
        java.lang.String cepDestino,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "fechaPlpVariosServicos", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.FechaPlpVariosServicos")
    @ResponseWrapper(localName = "fechaPlpVariosServicosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.FechaPlpVariosServicosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long fechaPlpVariosServicos(

        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "idPlpCliente", targetNamespace = "")
        java.lang.Long idPlpCliente,
        @WebParam(name = "cartaoPostagem", targetNamespace = "")
        java.lang.String cartaoPostagem,
        @WebParam(name = "listaEtiquetas", targetNamespace = "")
        java.util.List<java.lang.String> listaEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "geraDigitoVerificadorEtiquetas", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GeraDigitoVerificadorEtiquetas")
    @ResponseWrapper(localName = "geraDigitoVerificadorEtiquetasResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GeraDigitoVerificadorEtiquetasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> geraDigitoVerificadorEtiquetas(

        @WebParam(name = "etiquetas", targetNamespace = "")
        java.util.List<java.lang.String> etiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "obterEmbalagemLRS", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterEmbalagemLRS")
    @ResponseWrapper(localName = "obterEmbalagemLRSResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterEmbalagemLRSResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.EmbalagemLRSMaster> obterEmbalagemLRS()
 throws SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "validaEtiquetaPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidaEtiquetaPLP")
    @ResponseWrapper(localName = "validaEtiquetaPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidaEtiquetaPLPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean validaEtiquetaPLP(

        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaServicosValorDeclarado", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosValorDeclarado")
    @ResponseWrapper(localName = "buscaServicosValorDeclaradoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosValorDeclaradoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> buscaServicosValorDeclarado(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "consultaCEP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ConsultaCEP")
    @ResponseWrapper(localName = "consultaCEPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ConsultaCEPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.EnderecoERP consultaCEP(

        @WebParam(name = "cep", targetNamespace = "")
        java.lang.String cep
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "integrarUsuarioScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.IntegrarUsuarioScol")
    @ResponseWrapper(localName = "integrarUsuarioScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.IntegrarUsuarioScolResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean integrarUsuarioScol(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "pesquisarDimensoesServico", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarDimensoesServico")
    @ResponseWrapper(localName = "pesquisarDimensoesServicoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarDimensoesServicoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.DimensaoTO pesquisarDimensoesServico(

        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo,
        @WebParam(name = "embalagem", targetNamespace = "")
        java.lang.String embalagem
    );

    @WebMethod
    @RequestWrapper(localName = "pesquisarEmbalagensPorServico", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarEmbalagensPorServico")
    @ResponseWrapper(localName = "pesquisarEmbalagensPorServicoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarEmbalagensPorServicoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.TipoEmbalagem> pesquisarEmbalagensPorServico(

        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo
    );

    @WebMethod
    @RequestWrapper(localName = "atualizaRemessaAgrupada", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.AtualizaRemessaAgrupada")
    @ResponseWrapper(localName = "atualizaRemessaAgrupadaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.AtualizaRemessaAgrupadaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String atualizaRemessaAgrupada(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "solicitaPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaPLP")
    @ResponseWrapper(localName = "solicitaPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaPLPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String solicitaPLP(

        @WebParam(name = "idPlpMaster", targetNamespace = "")
        java.lang.Long idPlpMaster,
        @WebParam(name = "numEtiqueta", targetNamespace = "")
        java.lang.String numEtiqueta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "getStatusCartaoPostagem", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GetStatusCartaoPostagem")
    @ResponseWrapper(localName = "getStatusCartaoPostagemResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GetStatusCartaoPostagemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.StatusCartao getStatusCartaoPostagem(

        @WebParam(name = "numeroCartaoPostagem", targetNamespace = "")
        java.lang.String numeroCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "verificaModalTransporte", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaModalTransporte")
    @ResponseWrapper(localName = "verificaModalTransporteResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.VerificaModalTransporteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verificaModalTransporte(

        @WebParam(name = "codigoServico", targetNamespace = "")
        java.lang.String codigoServico,
        @WebParam(name = "cepOrigem", targetNamespace = "")
        java.lang.String cepOrigem,
        @WebParam(name = "cepDestino", targetNamespace = "")
        java.lang.String cepDestino,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaDataAtual", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaDataAtual")
    @ResponseWrapper(localName = "buscaDataAtualResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaDataAtualResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar buscaDataAtual()
;

    @WebMethod
    @RequestWrapper(localName = "buscaTarifaVale", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaTarifaVale")
    @ResponseWrapper(localName = "buscaTarifaValeResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaTarifaValeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.ValePostal buscaTarifaVale(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.String codAdministrativo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "codServico", targetNamespace = "")
        java.lang.String codServico,
        @WebParam(name = "cepOrigem", targetNamespace = "")
        java.lang.String cepOrigem,
        @WebParam(name = "cepDestino", targetNamespace = "")
        java.lang.String cepDestino,
        @WebParam(name = "peso", targetNamespace = "")
        java.lang.String peso,
        @WebParam(name = "codFormato", targetNamespace = "")
        java.lang.Integer codFormato,
        @WebParam(name = "comprimento", targetNamespace = "")
        java.lang.Double comprimento,
        @WebParam(name = "altura", targetNamespace = "")
        java.lang.Double altura,
        @WebParam(name = "largura", targetNamespace = "")
        java.lang.Double largura,
        @WebParam(name = "valorDeclarado", targetNamespace = "")
        java.lang.Double valorDeclarado,
        @WebParam(name = "servicoAdicional", targetNamespace = "")
        java.lang.String servicoAdicional
    ) throws SigepClienteException, Exception_Exception, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "validarPostagemSimultanea", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidarPostagemSimultanea")
    @ResponseWrapper(localName = "validarPostagemSimultaneaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidarPostagemSimultaneaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean validarPostagemSimultanea(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "codigoServico", targetNamespace = "")
        java.lang.Integer codigoServico,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "cepDestinatario", targetNamespace = "")
        java.lang.String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        br.com.marcelbraghini.infrastructure.correios.atendecliente.ColetaSimultanea coleta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "getStatusPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GetStatusPLP")
    @ResponseWrapper(localName = "getStatusPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.GetStatusPLPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.StatusPlp getStatusPLP(

        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.ObjetoPostal> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "pesquisarServicosAdicionais", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarServicosAdicionais")
    @ResponseWrapper(localName = "pesquisarServicosAdicionaisResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.PesquisarServicosAdicionaisResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.ServicoAdicionalTO> pesquisarServicosAdicionais(

        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo
    );

    @WebMethod
    @RequestWrapper(localName = "buscaServicosXServicosAdicionais", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosXServicosAdicionais")
    @ResponseWrapper(localName = "buscaServicosXServicosAdicionaisResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosXServicosAdicionaisResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> buscaServicosXServicosAdicionais(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SQLException_Exception, SigepClienteException;

    @WebMethod
    @RequestWrapper(localName = "cancelarPedidoScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CancelarPedidoScol")
    @ResponseWrapper(localName = "cancelarPedidoScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.CancelarPedidoScolResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.RetornoCancelamento cancelarPedidoScol(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.String codAdministrativo,
        @WebParam(name = "idPostagem", targetNamespace = "")
        java.lang.String idPostagem,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "bloquearObjeto", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BloquearObjeto")
    @ResponseWrapper(localName = "bloquearObjetoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BloquearObjetoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bloquearObjeto(

        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "tipoBloqueio", targetNamespace = "")
        br.com.marcelbraghini.infrastructure.correios.atendecliente.TipoBloqueio tipoBloqueio,
        @WebParam(name = "acao", targetNamespace = "")
        br.com.marcelbraghini.infrastructure.correios.atendecliente.Acao acao,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaContrato", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaContrato")
    @ResponseWrapper(localName = "buscaContratoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaContratoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.ContratoERP buscaContrato(

        @WebParam(name = "numero", targetNamespace = "")
        java.lang.String numero,
        @WebParam(name = "diretoria", targetNamespace = "")
        long diretoria,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "solicitaEtiquetas", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaEtiquetas")
    @ResponseWrapper(localName = "solicitaEtiquetasResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaEtiquetasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String solicitaEtiquetas(

        @WebParam(name = "tipoDestinatario", targetNamespace = "")
        java.lang.String tipoDestinatario,
        @WebParam(name = "identificador", targetNamespace = "")
        java.lang.String identificador,
        @WebParam(name = "idServico", targetNamespace = "")
        java.lang.Long idServico,
        @WebParam(name = "qtdEtiquetas", targetNamespace = "")
        java.lang.Integer qtdEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "solicitaXmlPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaXmlPlp")
    @ResponseWrapper(localName = "solicitaXmlPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitaXmlPlpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String solicitaXmlPlp(

        @WebParam(name = "idPlpMaster", targetNamespace = "")
        java.lang.Long idPlpMaster,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "validarPostagemReversa", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidarPostagemReversa")
    @ResponseWrapper(localName = "validarPostagemReversaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ValidarPostagemReversaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean validarPostagemReversa(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.String codAdministrativo,
        @WebParam(name = "codigoServico", targetNamespace = "")
        java.lang.String codigoServico,
        @WebParam(name = "cepDestinatario", targetNamespace = "")
        java.lang.String cepDestinatario,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "coleta", targetNamespace = "")
        br.com.marcelbraghini.infrastructure.correios.atendecliente.ColetaReversa coleta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaCliente", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaCliente")
    @ResponseWrapper(localName = "buscaClienteResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaClienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.ClienteERP buscaCliente(

        @WebParam(name = "idContrato", targetNamespace = "")
        java.lang.String idContrato,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaPagamentoEntrega", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaPagamentoEntrega")
    @ResponseWrapper(localName = "buscaPagamentoEntregaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaPagamentoEntregaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String buscaPagamentoEntrega(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "contrato", targetNamespace = "")
        java.lang.String contrato,
        @WebParam(name = "dataInicio", targetNamespace = "")
        java.lang.String dataInicio,
        @WebParam(name = "dataFim", targetNamespace = "")
        java.lang.String dataFim,
        @WebParam(name = "etiqueta", targetNamespace = "")
        java.lang.String etiqueta
    ) throws ErroMontagemRelatorio_Exception, SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "solicitarPostagemScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitarPostagemScol")
    @ResponseWrapper(localName = "solicitarPostagemScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.SolicitarPostagemScolResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String solicitarPostagemScol(

        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "buscaServicos", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicos")
    @ResponseWrapper(localName = "buscaServicosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaServicosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<br.com.marcelbraghini.infrastructure.correios.atendecliente.ServicoERP> buscaServicos(

        @WebParam(name = "idContrato", targetNamespace = "")
        java.lang.String idContrato,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException, AutenticacaoException;

    @WebMethod
    @RequestWrapper(localName = "obterMensagemParametrizada", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterMensagemParametrizada")
    @ResponseWrapper(localName = "obterMensagemParametrizadaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.ObterMensagemParametrizadaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public br.com.marcelbraghini.infrastructure.correios.atendecliente.MensagemParametrizadaTO obterMensagemParametrizada(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Short id
    );

    @WebMethod
    @RequestWrapper(localName = "buscaOpcoes", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaOpcoes")
    @ResponseWrapper(localName = "buscaOpcoesResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.marcelbraghini.infrastructure.correios.atendecliente.BuscaOpcoesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String buscaOpcoes(

        @WebParam(name = "listaObjetos", targetNamespace = "")
        java.util.List<java.lang.String> listaObjetos,
        @WebParam(name = "tipoResultado", targetNamespace = "")
        java.lang.String tipoResultado,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws SigepClienteException;
}
