
package br.com.marcelbraghini.infrastructure.correios.atendecliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-04-24T17:06:19.390-03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "AutenticacaoException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class AutenticacaoException extends java.lang.Exception {

    private java.lang.String faultInfo;

    public AutenticacaoException() {
        super();
    }

    public AutenticacaoException(String message) {
        super(message);
    }

    public AutenticacaoException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoException) {
        super(message);
        this.faultInfo = autenticacaoException;
    }

    public AutenticacaoException(String message, java.lang.String autenticacaoException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = autenticacaoException;
    }

    public java.lang.String getFaultInfo() {
        return this.faultInfo;
    }
}
