
package br.com.marcelbraghini.infrastructure.correios.atendecliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-04-24T17:06:19.412-03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "ErroMontagemRelatorio", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class ErroMontagemRelatorio_Exception extends java.lang.Exception {

    private br.com.marcelbraghini.infrastructure.correios.atendecliente.ErroMontagemRelatorio faultInfo;

    public ErroMontagemRelatorio_Exception() {
        super();
    }

    public ErroMontagemRelatorio_Exception(String message) {
        super(message);
    }

    public ErroMontagemRelatorio_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ErroMontagemRelatorio_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.ErroMontagemRelatorio erroMontagemRelatorio) {
        super(message);
        this.faultInfo = erroMontagemRelatorio;
    }

    public ErroMontagemRelatorio_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.ErroMontagemRelatorio erroMontagemRelatorio, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = erroMontagemRelatorio;
    }

    public br.com.marcelbraghini.infrastructure.correios.atendecliente.ErroMontagemRelatorio getFaultInfo() {
        return this.faultInfo;
    }
}
