
package br.com.marcelbraghini.infrastructure.correios.atendecliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-04-24T17:06:19.400-03:00
 * Generated source version: 3.4.2
 */

@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class Exception_Exception extends java.lang.Exception {

    private br.com.marcelbraghini.infrastructure.correios.atendecliente.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public br.com.marcelbraghini.infrastructure.correios.atendecliente.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
