
package br.com.marcelbraghini.infrastructure.correios.atendecliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-19T22:02:02.891-03:00
 * Generated source version: 3.4.4
 */

@WebFault(name = "SQLException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class SQLException_Exception extends java.lang.Exception {

    private br.com.marcelbraghini.infrastructure.correios.atendecliente.SQLException faultInfo;

    public SQLException_Exception() {
        super();
    }

    public SQLException_Exception(String message) {
        super(message);
    }

    public SQLException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SQLException_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.SQLException sqlException) {
        super(message);
        this.faultInfo = sqlException;
    }

    public SQLException_Exception(String message, br.com.marcelbraghini.infrastructure.correios.atendecliente.SQLException sqlException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = sqlException;
    }

    public br.com.marcelbraghini.infrastructure.correios.atendecliente.SQLException getFaultInfo() {
        return this.faultInfo;
    }
}
